module.exports = {
  AUTH_SETUP_SUCCESS: "AUTH_SETUP_SUCCESS",
  AUTH_SETUP_ALREADY_INSTALLED: "AUTH_SETUP_ALREADY_INSTALLED",
  AUTH_SETUP_FAILED: "AUTH_SETUP_FAILED",

  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_REFRESH_SUCCESS: "AUTH_REFRESH_SUCCESS",
  AUTH_ME_SUCCESS: "AUTH_ME_SUCCESS",

  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_USER_INACTIVE: "AUTH_USER_INACTIVE",

  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",

  AUTH_REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_EXPIRED: "AUTH_REFRESH_TOKEN_EXPIRED",

  AUTH_PERMISSION_DENIED: "AUTH_PERMISSION_DENIED",
  AUTH_ROLE_REQUIRED: "AUTH_ROLE_REQUIRED",

  AUTH_VALIDATION_ERROR: "AUTH_VALIDATION_ERROR",
  AUTH_INTERNAL_ERROR: "AUTH_INTERNAL_ERROR",

  AUTH_SESSIONS_SUCCESS: "AUTH_SESSIONS_SUCCESS",
  AUTH_LOGOUT_ALL_SUCCESS: "AUTH_LOGOUT_ALL_SUCCESS",
  AUTH_SESSION_LOGOUT_SUCCESS: "AUTH_SESSION_LOGOUT_SUCCESS",
  AUTH_SESSION_NOT_FOUND: "AUTH_SESSION_NOT_FOUND",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_CURRENT_PASSWORD_INVALID: "AUTH_CURRENT_PASSWORD_INVALID",
};